# Generated by Django 3.2.12 on 2026-02-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Latest evaluation score (0-100)')),
                ('completed', models.BooleanField(default=False, help_text='Whether the lesson has been marked as completed')),
                ('attempts', models.IntegerField(default=0, help_text='Number of evaluation attempts')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the user first started this lesson', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this lesson', null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the user accessed this lesson')),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Total time spent on this lesson (in minutes)')),
                ('review_count', models.IntegerField(default=0, help_text='Number of times the lesson was reviewed after completion')),
                ('metadata', models.JSONField(default=dict, help_text='Additional tracking data (engagement, difficulty ratings, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(help_text='The lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('user', models.ForeignKey(help_text='Learner', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the user started this course')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed this course', null=True)),
                ('overall_score', models.FloatField(default=0.0, help_text='Average score across all completed lessons')),
                ('metadata', models.JSONField(default=dict, help_text='Additional course-level metadata (pace, strengths, weaknesses)')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time the user accessed any lesson in this course')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='The course being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.course')),
                ('current_lesson', models.ForeignKey(blank=True, help_text='The lesson the user is currently working on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='courses.lesson')),
                ('user', models.ForeignKey(help_text='Learner', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress',
            },
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson', 'completed'], name='progress_le_user_id_649730_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'completed'], name='progress_le_user_id_a34390_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='progress_le_lesson__7d0f4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['user', 'course'], name='progress_co_user_id_220bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['user', 'completed_at'], name='progress_co_user_id_bcceea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('user', 'course')},
        ),
    ]
