# Generated by Django 3.2.12 on 2026-02-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('course_generation', 'Course Generation'), ('lesson_content', 'Lesson Content'), ('evaluation_questions', 'Evaluation Questions'), ('feedback', 'Feedback Generation'), ('other', 'Other')], db_index=True, help_text='Category of prompt', max_length=50)),
                ('input_prompt', models.TextField(help_text='The full prompt sent to the LLM')),
                ('context', models.TextField(blank=True, help_text='Retrieved context (RAG) used in the prompt')),
                ('response', models.TextField(help_text="LLM's response")),
                ('model_name', models.CharField(help_text="Name of the LLM model used (e.g., 'phi', 'mistral')", max_length=100)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Approximate token count (if available)', null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, help_text='Time taken for LLM response (milliseconds)', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the LLM call succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error details if the call failed')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (temperature, max_tokens, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'LLM Prompt Log',
                'verbose_name_plural': 'LLM Prompt Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='llmpromptlog',
            index=models.Index(fields=['prompt_type', 'created_at'], name='ai_engine_l_prompt__3abd22_idx'),
        ),
        migrations.AddIndex(
            model_name='llmpromptlog',
            index=models.Index(fields=['model_name', 'created_at'], name='ai_engine_l_model_n_eaecf3_idx'),
        ),
        migrations.AddIndex(
            model_name='llmpromptlog',
            index=models.Index(fields=['success'], name='ai_engine_l_success_66fa05_idx'),
        ),
    ]
