# Generated by Django 3.2.12 on 2026-02-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Main topic or subject area', max_length=200)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Difficulty level', max_length=20)),
                ('goal', models.TextField(help_text='Learning objective or goal stated by the user')),
                ('description', models.TextField(blank=True, help_text='AI-generated course description')),
                ('estimated_duration_hours', models.FloatField(blank=True, help_text='Estimated time to complete (in hours)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', help_text='Current status of the course', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Learner who requested this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Module title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='What this module covers')),
                ('objectives', models.JSONField(default=list, help_text='Learning objectives for this module (list of strings)')),
                ('order', models.IntegerField(help_text='Sequential order within the course (0-based)')),
                ('estimated_duration_hours', models.FloatField(blank=True, help_text='Estimated time to complete this module', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Parent course', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this lesson covers')),
                ('content', models.TextField(help_text='Main lesson content (text, explanations, examples)')),
                ('content_type', models.CharField(choices=[('video', 'Video-based'), ('text', 'Text/Reading'), ('interactive', 'Interactive/Hands-on'), ('mixed', 'Mixed Media')], default='mixed', help_text='Primary content delivery method', max_length=20)),
                ('objectives', models.JSONField(default=list, help_text='Specific learning objectives (list of strings)')),
                ('prerequisites', models.JSONField(default=list, help_text='Concepts that should be understood before this lesson')),
                ('order', models.IntegerField(help_text='Sequential order within the module (0-based)')),
                ('estimated_duration_minutes', models.IntegerField(blank=True, help_text='Estimated time to complete (in minutes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Parent module', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
                ('resources', models.ManyToManyField(blank=True, help_text='Associated learning resources', related_name='lessons', to='research.Resource')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='courses_mod_course__20183c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='courses_les_module__4accd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'status', 'created_at'], name='courses_cou_user_id_b5d5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
    ]
