# Generated by Django 3.2.12 on 2026-02-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(help_text='Unique identifier for this index', max_length=100, unique=True)),
                ('model_name', models.CharField(help_text="Name of the embedding model used (e.g., 'all-MiniLM-L6-v2')", max_length=200)),
                ('dimension', models.IntegerField(help_text='Embedding vector dimension')),
                ('total_vectors', models.IntegerField(default=0, help_text='Total number of vectors in the index')),
                ('file_path', models.CharField(help_text='File system path to the persisted FAISS index', max_length=500)),
                ('metadata', models.JSONField(default=dict, help_text='Additional index metadata (params, stats, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedding Index',
                'verbose_name_plural': 'Embedding Indexes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('documentation', 'Documentation'), ('article', 'Article'), ('book', 'Book'), ('other', 'Other')], db_index=True, help_text='Type of learning resource', max_length=20)),
                ('url', models.URLField(help_text='Original URL of the resource', max_length=500, unique=True)),
                ('title', models.CharField(help_text='Title of the resource', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Brief description or summary')),
                ('transcript_text', models.TextField(blank=True, help_text='Full transcript or extracted text content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (author, duration, views, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(help_text='Text content of this chunk')),
                ('chunk_index', models.IntegerField(help_text='Sequential index within the resource (0-based)')),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count')),
                ('metadata', models.JSONField(default=dict, help_text='Chunk-specific metadata (timestamp, section, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(help_text='Parent resource', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='research.resource')),
            ],
            options={
                'ordering': ['resource', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'created_at'], name='research_re_resourc_f8e13c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcechunk',
            index=models.Index(fields=['resource', 'chunk_index'], name='research_re_resourc_92f7c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcechunk',
            unique_together={('resource', 'chunk_index')},
        ),
    ]
